function MessageFeed() {
  var self = this;
  self.lastMessageIndexReceived = ko.observable(0); //message index = the message feed index generated by aspire-server (mempool tx do not have indexes and indexes CAN shift back during reorgs)
  self.lastMessageSeqReceived = ko.observable(0); //message seq = the message feed sequence number generated by aspireblocks's aspirewallet module (mempool tx DO have indexes, and seqs DO NOT shift back during reorgs)
  self.POLL_INTERVAL = 30000; // poll the server every 30 seconds

  self.init = function(last_message_index, cw_last_message_seq) {
    self.lastMessageIndexReceived(last_message_index);
    self.lastMessageSeqReceived(cw_last_message_seq);
    
    //kick off the loop to poll the message queue
    self.checkMessageQueue();
  }

  self.checkMessageQueue = function() {
    var event = null, result = null;

    $.jqlog.debug("checkMessageQueue. last_seq: " + self.lastMessageSeqReceived());

    //poll the server for new messages
    nonFailoverAPI("get_latest_wallet_messages", {'last_seq': self.lastMessageSeqReceived()}, 
    function(messages) {
      for (var i = 0; i < messages.length; i++) {
        self.parseMessage(messages[i]['_id'], messages[i]['when'], messages[i]['message']);
      }

      setTimeout(function() { self.checkMessageQueue(); }, self.POLL_INTERVAL);
    }, function(jqXHR, textStatus, errorThrown, endpoint) {
      var message = describeError(jqXHR, textStatus, errorThrown);
      $.jqlog.warn("Could not pull latest wallet messages; Error: " + message);
      
      setTimeout(function() { self.checkMessageQueue(); }, self.POLL_INTERVAL);
    });
  }

  self.getTxHash = function(message) {
    var txHash = message['event'] || message['tx_hash'] || (message['tx0_hash'] + message['tx1_hash']) || null;
    if (!txHash)
      $.jqlog.warn("Cannot derive a txHash for IDX " + message['_message_index'] + " (category: " + message['_category'] + ")");
    return txHash;
  }

  self.parseMempoolTransaction = function(txHash, category, message) {
    message['bindings'] = JSON.parse(message['bindings']);
    message['bindings']['mempool'] = true;

    var displayTx = false;

    if (!WALLET.getAddressObj(message['bindings']['source'])) {
      if (category == 'sends') {
        if (WALLET.getAddressObj(message['bindings']['destination'])) {
          displayTx = true;
        }
      } else if (category == 'issuances' && message['bindings']['transfer']) {
        if (WALLET.getAddressObj(message['bindings']['issuer'])) {
          message['bindings']['transfer_destination'] = message['bindings']['issuer'];
          displayTx = true;
        }
      } else if (category == 'dividends') {
        if (WALLET.isAssetHolder(message['bindings']['asset'])) {
          displayTx = true;
        }
      }
    }

    if (displayTx) {
      PENDING_ACTION_FEED.add(txHash, category, message['bindings']);

      /*var asset1 = message['bindings']['asset'] || 'GASP';
      WALLET.getAssetsDivisibility([asset1], function(divisibility) {

        message['bindings']['divisible'] = divisibility[asset1];
        message['bindings']['tx_index'] = message['_message_index'];

        if (category == 'dividends') {

          var asset2 = message['bindings']['dividend_asset'];
          WALLET.getAssetsDivisibility([asset2], function(asset_divisibility) {
            message['bindings']['dividend_asset_divisible'] = asset_divisibility[asset2];
            PENDING_ACTION_FEED.add(txHash, category, message['bindings']);
          });

        } else {
          PENDING_ACTION_FEED.add(txHash, category, message['bindings']);
        }

      });*/
    }

  }

  self.parseMessage = function(seq, when, message) {
    if (!message || (message.substring && _.startsWith(message, "<html>"))) return;
    //^ sometimes nginx can trigger this via its proxy handling it seems, with a blank payload (or a html 502 Bad Gateway
    // payload) -- especially if the backend server reloads. Just ignore it.
    // Also, a message may be sent over as None if it is a stub message conterblock uses to initialize the sequence count

    //NOTE: we use the message sequence that the counterblock counterwallet module generates, as it takes into account mempool transactions
    // (which come across the counterblock counterwallet feed like any other message)
    // the message_index created by the counterparty-server message feed DOES NOT generate message_indexes for mempool transactions
    assert(self.lastMessageIndexReceived(), "lastMessageIndexReceived is not defined!");

    $.jqlog.info("feed:receive IDX=" + message['_message_index']);

    if (seq != self.lastMessageSeqReceived() + 1) {
      $.jqlog.warn("Received message seq (" + seq + ") is != lastMessageSeqReceived (" + self.lastMessageSeqReceived() + "). Message: " + JSON.stringify(message));
      return;
    }

    self.lastMessageSeqReceived(self.lastMessageSeqReceived() + 1);
    var txHash = self.getTxHash(message);
    var category = message['_category'];

    //Handle zeroconf transactions
    if (message['_message_index'] == 'mempool') {
      self.parseMempoolTransaction(txHash, category, message);
      return;
    }

    // Warn on messages that are not sent in order (should never happen)
    if (message['_message_index'] > self.lastMessageIndexReceived() + 1) {
      $.jqlog.warn("Received message index (" + message['_message_index'] + ") is != lastMessageIndexReceived (" + self.lastMessageIndexReceived() + "). Message: " + JSON.stringify(message));
      return;
    }

    //Otherwise, normal case: process the message
    assert(self.lastMessageIndexReceived() + 1 == message['_message_index'], "Message feed resync counter increment oddity...?");
    $.jqlog.info("feed:PROCESS MESSAGE=" + category + ", IDX=" + message['_message_index'] + " (last idx: "
      + self.lastMessageIndexReceived() + "), TX_HASH=" + txHash + ", CONTENTS=" + JSON.stringify(message));

    self.lastMessageIndexReceived(self.lastMessageIndexReceived() + 1);

    //Detect a reorg and refresh the current page if so.
    if (message['_command'] == 'reorg') {
      //Don't need to adjust the message index
      self.lastMessageIndexReceived(message['_last_message_index']);
      $.jqlog.warn("feed:Blockchain reorganization at block " + message['block_index']
        + "; last message idx reset to " + self.lastMessageIndexReceived());
      setTimeout(function() { WALLET.refreshAspireBalances(WALLET.getAddressesList(), checkURL); }, randomIntFromInterval(1, 5) * 1000);
      //^ refresh the current page to regrab the fresh data (give cwd a second to sync up though)
      // also, wait a random interval to do this between 1 and 5 seconds, to avoid dog-piling the server
      //TODO/BUG??: do we need to "roll back" old messages on the bad chain???
      return;
    }

    //increment stored networkBlockHeight off of the feed, if possible (allows us to more quickly update this then
    // just relying on 5 minute polling for new BTC balances)
    if (message['block_index'])
      WALLET.networkBlockHeight(message['block_index']);

    if (message['_command'] != 'insert')
      return;

    //If we received an action originating from an address in our wallet that was marked invalid by the network, let the user know
    // (do this even in cases where the entry does not exist in pendingActions, as the user could have logged out and back in)
    if (message['_status'] && _.startsWith(message['_status'], 'invalid') && WALLET.getAddressObj(message['source'])) {
      var actionText = PendingActionViewModel.calcText(category, message); //nice "good enough" shortcut method here
      bootbox.alert("<b class='errorColor'>" + i18n.t('network_processing_failed') + ":</b><br/><br/>"
        + actionText + "<br/><br/><b>" + i18n.t("reason") + ":</b> " + message['_status']);
    }

    //Insert the message into the stats page (if it has been initialized)
    if (window.hasOwnProperty('STATS_TXN_HISTORY')) {
      window.STATS_TXN_HISTORY.addMessage(message);
    }

    //remove any pending message from the pending actions pane (we do this before we filter out invalid messages
    // because we need to be able to remove a pending action that was marked invalid as well)
    PENDING_ACTION_FEED.remove(txHash, category);

    if (_.startsWith(message['_status'], 'invalid'))
      return; //ignore message

    //notify the user in the notification pane
    NOTIFICATION_FEED.add(category, message);
    //^ especially with issuances, it's important that this line come before we modify state below

    // Have the action take effect (i.e. everything besides notifying the user in the notifcations pane, which was done above)
    if (category == "balances") {
      // DO NOTHING
    } else if (category == "credits" || category == "debits") {
      if (WALLET.getAddressObj(message['address'])) {
        WALLET.updateBalance(message['address'], message['asset'], message['_balance']);
      }
    } else if (category == "broadcasts") {
    } else if (category == "proofofwork") {
    } else if (category == "dividends") {
    } else if (category == "issuances") {
      //the 'asset' field is == asset_longname for subassets
      var addressesWithAsset = WALLET.getAddressesWithAsset(message['asset']);
      for (var i = 0; i < addressesWithAsset.length; i++) {
        WALLET.getAddressObj(addressesWithAsset[i]).addOrUpdateAsset(message['asset'], message, null);
      }
      //Also, if this is a new asset creation, or a transfer to an address that doesn't have the asset yet
      if (WALLET.getAddressObj(message['issuer']) && addressesWithAsset.length && !(addressesWithAsset.indexOf(message['issuer']) != -1)) {
        failoverAPI("get_assets_info", {'assetsList': [message['asset']]}, function(assetsInfo, endpoint) {
          WALLET.getAddressObj(message['issuer']).addOrUpdateAsset(message['asset'], assetsInfo[0], null); //will show with a 0 balance
        });
      }

    } else if (category == "sends") {
      //the effects of a send are handled based on the credit and debit messages it creates, so nothing to do here
    } else {
      $.jqlog.error("Unknown message category: " + category);
    }
  }

}
